//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberArk.Extensions.ServiceNow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberArk.Extensions.ServiceNow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  response validation failed. Null JSON returned..
        /// </summary>
        internal static string ActionResponseFailure {
            get {
                return ResourceManager.GetString("ActionResponseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  response validated. JSON indicates action was successful..
        /// </summary>
        internal static string ActionResponseSuccess {
            get {
                return ResourceManager.GetString("ActionResponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested URI does not represent any resource.
        /// </summary>
        internal static string BadRequestInvalidResource {
            get {
                return ResourceManager.GetString("BadRequestInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 Bad Request Failure. Checking failure type.
        /// </summary>
        internal static string BadRequestRecieved {
            get {
                return ResourceManager.GetString("BadRequestRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Action Ended Successfully..
        /// </summary>
        internal static string ChangeSuccess {
            get {
                return ResourceManager.GetString("ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown 40X Error.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException: Connection Failure. Unable to connect to the remote server..
        /// </summary>
        internal static string HttpConnectFailure {
            get {
                return ResourceManager.GetString("HttpConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Request Exeption: Response status code does not indicate success: 400 (Bad Request). No Inner Exception available..
        /// </summary>
        internal static string HttpGeneralRequestError {
            get {
                return ResourceManager.GetString("HttpGeneralRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException: Name Resolution Error. The remote name could not be resolved..
        /// </summary>
        internal static string HttpNameResolutionFailure {
            get {
                return ResourceManager.GetString("HttpNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non 200 Http Response Recieved. The Identity Web Server is not available or the user credentials were not accepted..
        /// </summary>
        internal static string HttpRequestException {
            get {
                return ResourceManager.GetString("HttpRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Request Exeption: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
        /// </summary>
        internal static string HttpSecureChannelError {
            get {
                return ResourceManager.GetString("HttpSecureChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException: Unhandled..
        /// </summary>
        internal static string HttpUnhandledInnerException {
            get {
                return ResourceManager.GetString("HttpUnhandledInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException: Unhandled..
        /// </summary>
        internal static string HttpUnhandledInnerWebException {
            get {
                return ResourceManager.GetString("HttpUnhandledInnerWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Action Ended Successfully..
        /// </summary>
        internal static string LogonSuccess {
            get {
                return ResourceManager.GetString("LogonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  request response recieved. Validating JSON response success value..
        /// </summary>
        internal static string RecieveActionResponse {
            get {
                return ResourceManager.GetString("RecieveActionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile Action Ended Successfully..
        /// </summary>
        internal static string ReconcileSuccess {
            get {
                return ResourceManager.GetString("ReconcileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request for .
        /// </summary>
        internal static string SendActionRequest {
            get {
                return ResourceManager.GetString("SendActionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract sys_id from ServiceNow Server response..
        /// </summary>
        internal static string SysIdError {
            get {
                return ResourceManager.GetString("SysIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted sys_id from ServiceNow Server response..
        /// </summary>
        internal static string SysIdSuccess {
            get {
                return ResourceManager.GetString("SysIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException: Unhandled -.
        /// </summary>
        internal static string UnhandledWebException {
            get {
                return ResourceManager.GetString("UnhandledWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Action Ended Successfully..
        /// </summary>
        internal static string VerifySuccess {
            get {
                return ResourceManager.GetString("VerifySuccess", resourceCulture);
            }
        }
    }
}
